package com.sentry.app.features.trainee.curriculum

object OwaspCurriculum {
    val modules: List<OwaspTrainingModule> = listOf(
        OwaspTrainingModule(
            id = "owasp-a01-broken-access-control",
            owaspId = "A01",
            title = "Broken Access Control",
            difficulty = "Foundation",
            summary = "Access control makes sure people can only view or change the data and functions they are allowed to use.",
            workplaceTakeaway = "Never bypass approval, change IDs in URLs, or use someone else's access. Report access that looks too broad.",
            scenario = "You work in HR and receive a link to view your own leave record. You notice the URL ends with employeeId=1042. A colleague asks you to change the number to 1043 to check whether their record appears because they cannot log in. What should you do?",
            sourceReference = "A01_2025-Broken_Access_Control.md",
            correctAnswerId = "report",
            options = listOf(
                OwaspAnswerOption(
                    id = "try_it",
                    label = "A",
                    text = "Change the employee ID quickly to see if the system blocks you.",
                    isCorrect = false,
                    feedback = "This is the wrong choice. OWASP A01 explains that broken access control happens when users can act outside their intended permissions. Testing another person's record without authorization can expose private data. The correct action is to stop and report the possible access control weakness.",
                ),
                OwaspAnswerOption(
                    id = "share_link",
                    label = "B",
                    text = "Send your link to the colleague so they can try it themselves.",
                    isCorrect = false,
                    feedback = "This is risky because it spreads a potentially vulnerable link and may expose your own session context. OWASP A01 focuses on preventing unauthorized access. The safe action is to report the suspected issue instead of sharing or experimenting.",
                ),
                OwaspAnswerOption(
                    id = "report",
                    label = "C",
                    text = "Do not change the URL. Report the possible access control issue to IT security.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A01 says access control should prevent users from acting outside their permissions. Reporting the issue protects employee records and gives IT a chance to verify whether the system enforces authorization on the server.",
                ),
                OwaspAnswerOption(
                    id = "screenshot",
                    label = "D",
                    text = "Try the change, take screenshots as proof, then report it.",
                    isCorrect = false,
                    feedback = "This still creates unauthorized access. Evidence is useful only when collected safely. According to OWASP A01, access control failures can disclose or modify data. Report the concern without attempting to access another person's record.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a02-security-misconfiguration",
            owaspId = "A02",
            title = "Security Misconfiguration",
            difficulty = "Foundation",
            summary = "Security misconfiguration happens when systems are deployed with unsafe defaults, exposed admin tools, verbose errors, or unnecessary features.",
            workplaceTakeaway = "Treat default passwords, sample apps, exposed dashboards, and detailed errors as security issues that must be fixed or escalated.",
            scenario = "A vendor installs a new internal reporting tool. During testing you find an admin page still using the default username and password from the product manual. The team wants to leave it until after launch. What should you do?",
            sourceReference = "A02_2025-Security_Misconfiguration.md",
            correctAnswerId = "block_launch",
            options = listOf(
                OwaspAnswerOption(
                    id = "leave_it",
                    label = "A",
                    text = "Leave it for now because the tool is only internal.",
                    isCorrect = false,
                    feedback = "This is incorrect. OWASP A02 notes that default accounts and exposed admin tools are common misconfigurations. Internal systems can still be reached by attackers or misused by insiders. The launch should wait until default credentials are removed.",
                ),
                OwaspAnswerOption(
                    id = "email_password",
                    label = "B",
                    text = "Email the default password to the team so everyone remembers to change it later.",
                    isCorrect = false,
                    feedback = "This makes the problem worse by distributing a known password. OWASP A02 recommends secure, repeatable configuration and removal of unsafe defaults. The correct action is to block release until the admin page is secured.",
                ),
                OwaspAnswerOption(
                    id = "block_launch",
                    label = "C",
                    text = "Escalate it as a release blocker until the default account is disabled or changed.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A02 gives default accounts and sample admin consoles as classic security misconfigurations. Blocking release until the configuration is fixed prevents easy takeover.",
                ),
                OwaspAnswerOption(
                    id = "hide_url",
                    label = "D",
                    text = "Hide the admin URL from normal users and launch anyway.",
                    isCorrect = false,
                    feedback = "Hiding a URL is not security control. Attackers can discover paths. OWASP A02 emphasizes secure configuration, not obscurity. The default account must be disabled or changed before launch.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a03-software-supply-chain",
            owaspId = "A03",
            title = "Software Supply Chain Failures",
            difficulty = "Intermediate",
            summary = "Software supply chain failures involve unsafe dependencies, untrusted packages, compromised vendors, or missing component monitoring.",
            workplaceTakeaway = "Install software and updates only from approved sources, and report unexpected package or vendor changes.",
            scenario = "A colleague shares a link to a free browser plugin that promises to export customer records faster than the approved tool. It is not listed in the company software catalog, but it has good reviews online. What should you do?",
            sourceReference = "A03_2025-Software_Supply_Chain_Failures.md",
            correctAnswerId = "verify_source",
            options = listOf(
                OwaspAnswerOption(
                    id = "install",
                    label = "A",
                    text = "Install it because reviews suggest it is safe.",
                    isCorrect = false,
                    feedback = "This is unsafe. OWASP A03 warns that untrusted components can run with the same privileges as the application or user. Good reviews do not prove integrity. Use approved software channels.",
                ),
                OwaspAnswerOption(
                    id = "test_personal",
                    label = "B",
                    text = "Try it on a personal laptop first, then install it at work if it works.",
                    isCorrect = false,
                    feedback = "Testing on a personal device does not verify software integrity and may expose personal data. OWASP A03 recommends trusted sources, component monitoring, and secure supply chain controls.",
                ),
                OwaspAnswerOption(
                    id = "verify_source",
                    label = "C",
                    text = "Do not install it. Ask IT/security to verify and approve the tool first.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A03 focuses on risks from untrusted components and compromised supply chains. Approval and verification reduce the chance of malicious or vulnerable software entering the organization.",
                ),
                OwaspAnswerOption(
                    id = "ask_colleague",
                    label = "D",
                    text = "Install it only if the colleague confirms they already used it.",
                    isCorrect = false,
                    feedback = "A colleague's experience is not a supply chain control. OWASP A03 calls for monitoring and trusted component sources. The safe choice is formal verification before installation.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a04-cryptographic-failures",
            owaspId = "A04",
            title = "Cryptographic Failures",
            difficulty = "Intermediate",
            summary = "Cryptographic failures happen when sensitive data is not properly protected in storage or transit.",
            workplaceTakeaway = "Use approved encrypted channels and never send sensitive business data through insecure links or unapproved storage.",
            scenario = "A manager asks you to send a spreadsheet containing customer IDs and phone numbers to an external consultant. Their email server rejects large attachments, so they suggest uploading it to a public file-sharing link without a password. What should you do?",
            sourceReference = "A04_2025-Cryptographic_Failures.md",
            correctAnswerId = "secure_channel",
            options = listOf(
                OwaspAnswerOption(
                    id = "public_link",
                    label = "A",
                    text = "Upload it to the public link because the consultant needs it urgently.",
                    isCorrect = false,
                    feedback = "This is wrong. OWASP A04 is about failures to protect sensitive data. A public unprotected link can expose customer information. Use an approved encrypted sharing channel.",
                ),
                OwaspAnswerOption(
                    id = "rename_file",
                    label = "B",
                    text = "Rename the file to something harmless before uploading it.",
                    isCorrect = false,
                    feedback = "Renaming does not encrypt or protect data. OWASP A04 focuses on strong protection for sensitive data in transit and storage. The correct action is to use an approved secure channel.",
                ),
                OwaspAnswerOption(
                    id = "secure_channel",
                    label = "C",
                    text = "Use the approved encrypted file transfer method or ask IT for a secure alternative.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A04 warns that sensitive data must be protected with appropriate cryptography. Approved encrypted transfer reduces the risk of disclosure.",
                ),
                OwaspAnswerOption(
                    id = "send_partial",
                    label = "D",
                    text = "Split the spreadsheet into smaller files and email them normally.",
                    isCorrect = false,
                    feedback = "Smaller files are still sensitive. OWASP A04 is not about file size; it is about protecting sensitive data. Use approved encryption and access control.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a05-injection",
            owaspId = "A05",
            title = "Injection",
            difficulty = "Intermediate",
            summary = "Injection happens when untrusted input is treated as a command or query instead of data.",
            workplaceTakeaway = "Never paste unverified commands or query fragments into business systems. Report forms that behave strangely with special characters.",
            scenario = "A support dashboard lets staff search customer records. A user sends you the text `' OR '1'='1` and says to paste it into the search box to find their missing record faster. What should you do?",
            sourceReference = "A05_2025-Injection.md",
            correctAnswerId = "report_input",
            options = listOf(
                OwaspAnswerOption(
                    id = "paste",
                    label = "A",
                    text = "Paste the text exactly as given to see whether it finds the record.",
                    isCorrect = false,
                    feedback = "This is unsafe. OWASP A05 explains that injection occurs when untrusted input changes a query or command. The text looks like an injection payload and should not be tested in production.",
                ),
                OwaspAnswerOption(
                    id = "edit_payload",
                    label = "B",
                    text = "Remove the quotes and try a simplified version.",
                    isCorrect = false,
                    feedback = "Editing suspicious input does not make it safe. OWASP A05 recommends treating user input as data and using safe validation. Report the suspicious payload instead.",
                ),
                OwaspAnswerOption(
                    id = "report_input",
                    label = "C",
                    text = "Do not paste it. Report the suspicious input and search using normal customer identifiers.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A05 highlights untrusted input as the root of injection risk. Reporting the payload protects the system and gives developers a chance to verify input handling safely.",
                ),
                OwaspAnswerOption(
                    id = "try_test",
                    label = "D",
                    text = "Try it only in a low-traffic period so fewer users are affected.",
                    isCorrect = false,
                    feedback = "Timing does not remove injection risk. OWASP A05 examples show that unsafe input can expose or damage data. Do not run suspicious payloads in production.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a06-insecure-design",
            owaspId = "A06",
            title = "Insecure Design",
            difficulty = "Advanced",
            summary = "Insecure design means the system workflow itself allows abuse, even if the code works as written.",
            workplaceTakeaway = "When a process allows obvious misuse, escalate the design risk instead of treating it as only a user mistake.",
            scenario = "A promotion system gives a discount for each referral. You notice the same employee can create unlimited referral codes for themselves because the workflow never checks ownership. What should you do?",
            sourceReference = "A06_2025-Insecure_Design.md",
            correctAnswerId = "raise_design",
            options = listOf(
                OwaspAnswerOption(
                    id = "use_codes",
                    label = "A",
                    text = "Use a few referral codes because the system allows it.",
                    isCorrect = false,
                    feedback = "This abuses a design flaw. OWASP A06 focuses on business logic and design weaknesses that allow unwanted behavior. The correct response is to raise the design risk.",
                ),
                OwaspAnswerOption(
                    id = "ignore",
                    label = "B",
                    text = "Ignore it because there is no error message.",
                    isCorrect = false,
                    feedback = "A design flaw may not produce an error. OWASP A06 warns that systems can be insecure by design even when they function normally. Report the issue.",
                ),
                OwaspAnswerOption(
                    id = "raise_design",
                    label = "C",
                    text = "Report the workflow as a business logic risk and recommend abuse checks.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A06 encourages secure design and threat modeling for business logic. Ownership checks, limits, and abuse controls should be designed into the workflow.",
                ),
                OwaspAnswerOption(
                    id = "tell_team",
                    label = "D",
                    text = "Tell colleagues informally so everyone avoids using the loophole.",
                    isCorrect = false,
                    feedback = "Informal warnings do not fix insecure design. OWASP A06 requires design-level controls. The issue should be formally reported and tracked.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a07-authentication-failures",
            owaspId = "A07",
            title = "Authentication Failures",
            difficulty = "Foundation",
            summary = "Authentication failures allow attackers to guess, reuse, steal, or bypass credentials and sessions.",
            workplaceTakeaway = "Use unique passwords, MFA, verified login pages, and immediate reporting for suspicious sign-in activity.",
            scenario = "You receive an MFA approval prompt on your phone while you are not logging in. A minute later, another prompt appears. What should you do?",
            sourceReference = "A07_2025-Authentication_Failures.md",
            correctAnswerId = "deny_report",
            options = listOf(
                OwaspAnswerOption(
                    id = "approve",
                    label = "A",
                    text = "Approve one prompt to stop the notifications.",
                    isCorrect = false,
                    feedback = "This is dangerous. OWASP A07 covers authentication attacks, including credential abuse. An unexpected MFA prompt may mean someone has your password. Deny it and report it.",
                ),
                OwaspAnswerOption(
                    id = "ignore",
                    label = "B",
                    text = "Ignore the prompts and continue working.",
                    isCorrect = false,
                    feedback = "Ignoring repeated MFA prompts misses a possible account attack. OWASP A07 recommends defenses against credential attacks. Deny, report, and change your password if instructed.",
                ),
                OwaspAnswerOption(
                    id = "deny_report",
                    label = "C",
                    text = "Deny the prompts and report the suspicious login attempt immediately.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A07 highlights risks from credential stuffing and weak authentication. Unexpected MFA prompts should be denied and reported because they may indicate an active account takeover attempt.",
                ),
                OwaspAnswerOption(
                    id = "ask_chat",
                    label = "D",
                    text = "Ask in a public chat whether anyone else is seeing prompts.",
                    isCorrect = false,
                    feedback = "Public chat may spread confusion and delay response. The correct path is to deny the prompt and report through the approved security channel.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a08-integrity-failures",
            owaspId = "A08",
            title = "Software or Data Integrity Failures",
            difficulty = "Advanced",
            summary = "Integrity failures happen when software, updates, plugins, or data are trusted without verifying that they are authentic and unchanged.",
            workplaceTakeaway = "Do not run unsigned updates, untrusted plugins, or modified data files outside approved verification processes.",
            scenario = "A router used by your branch office shows a firmware update from an unofficial website. The page says the update fixes performance issues, but the file is unsigned and not from the vendor portal. What should you do?",
            sourceReference = "A08_2025-Software_or_Data_Integrity_Failures.md",
            correctAnswerId = "vendor_only",
            options = listOf(
                OwaspAnswerOption(
                    id = "install",
                    label = "A",
                    text = "Install it because performance problems affect business operations.",
                    isCorrect = false,
                    feedback = "This is unsafe. OWASP A08 warns about updates that are applied without integrity verification. Unsigned firmware can be malicious or modified.",
                ),
                OwaspAnswerOption(
                    id = "scan",
                    label = "B",
                    text = "Download it and rely on antivirus scanning before installing.",
                    isCorrect = false,
                    feedback = "Antivirus scanning is not a substitute for authenticity and integrity checks. OWASP A08 emphasizes verifying updates through trusted mechanisms such as signatures and vendor sources.",
                ),
                OwaspAnswerOption(
                    id = "vendor_only",
                    label = "C",
                    text = "Do not install it. Use only vendor-approved, signed firmware through the official process.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A08 gives unsigned updates as a key example of integrity failure. Use trusted vendor sources and signed updates so attackers cannot replace software with malicious versions.",
                ),
                OwaspAnswerOption(
                    id = "install_after_hours",
                    label = "D",
                    text = "Install it after hours so any disruption affects fewer users.",
                    isCorrect = false,
                    feedback = "Installing at a quiet time does not solve integrity risk. The issue is whether the update is authentic and trusted. Use the official signed update path.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a09-logging-alerting",
            owaspId = "A09",
            title = "Security Logging and Alerting Failures",
            difficulty = "Intermediate",
            summary = "Logging and alerting failures prevent teams from detecting, investigating, and responding to attacks.",
            workplaceTakeaway = "Escalate suspicious activity through channels that create a record. Do not handle security incidents only by word of mouth.",
            scenario = "You see three failed admin login attempts followed by a successful login from an unusual country in the dashboard audit view. The manager says to mention it verbally in tomorrow's meeting. What should you do?",
            sourceReference = "A09_2025-Security_Logging_and_Alerting_Failures.md",
            correctAnswerId = "create_incident",
            options = listOf(
                OwaspAnswerOption(
                    id = "wait",
                    label = "A",
                    text = "Wait for the meeting because the login eventually succeeded.",
                    isCorrect = false,
                    feedback = "This delays response. OWASP A09 shows that weak logging and alerting can let breaches continue unnoticed. Suspicious login patterns need timely recorded escalation.",
                ),
                OwaspAnswerOption(
                    id = "verbal",
                    label = "B",
                    text = "Tell a colleague verbally and assume they will handle it.",
                    isCorrect = false,
                    feedback = "Verbal reporting may leave no audit trail. OWASP A09 emphasizes logging, monitoring, and alerting. Create an incident record through the approved channel.",
                ),
                OwaspAnswerOption(
                    id = "create_incident",
                    label = "C",
                    text = "Create or escalate a security incident with the relevant log details immediately.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A09 highlights the need to detect and respond to suspicious events. A recorded incident with log details gives the security team evidence to investigate quickly.",
                ),
                OwaspAnswerOption(
                    id = "disable_account",
                    label = "D",
                    text = "Disable the account yourself without following the incident process.",
                    isCorrect = false,
                    feedback = "Immediate containment may be needed, but it must follow the approved incident process. The best answer here is to escalate with log details so the right responders can act and preserve evidence.",
                ),
            ),
        ),
        OwaspTrainingModule(
            id = "owasp-a10-exceptional-conditions",
            owaspId = "A10",
            title = "Mishandling Exceptional Conditions",
            difficulty = "Advanced",
            summary = "Exceptional condition failures occur when errors, failures, race conditions, or partial transactions expose data or leave systems in unsafe states.",
            workplaceTakeaway = "Treat detailed errors, failed transactions, and repeated crashes as security signals, not just technical annoyances.",
            scenario = "During payment processing, a network error appears after the debit step. The system shows a detailed database error and lets you click retry repeatedly. What should you do?",
            sourceReference = "A10_2025-Mishandling_of_Exceptional_Conditions.md",
            correctAnswerId = "stop_report",
            options = listOf(
                OwaspAnswerOption(
                    id = "retry_many",
                    label = "A",
                    text = "Click retry several times until the transaction completes.",
                    isCorrect = false,
                    feedback = "This can worsen a partial transaction or duplicate processing. OWASP A10 includes state corruption and transaction failures as exceptional condition risks. Stop and report the issue.",
                ),
                OwaspAnswerOption(
                    id = "copy_error_public",
                    label = "B",
                    text = "Post the full database error in a public team chat for help.",
                    isCorrect = false,
                    feedback = "Detailed errors can expose sensitive system information. OWASP A10 warns that error handling can leak details attackers use. Report through the approved support or incident channel.",
                ),
                OwaspAnswerOption(
                    id = "stop_report",
                    label = "C",
                    text = "Stop retrying, preserve the reference number, and report the failed transaction securely.",
                    isCorrect = true,
                    feedback = "Correct. OWASP A10 explains that mishandled failures can cause state corruption or sensitive disclosure. Preserving evidence and reporting securely lets support investigate without creating duplicate or unsafe actions.",
                ),
                OwaspAnswerOption(
                    id = "refresh",
                    label = "D",
                    text = "Refresh the browser and start the payment again from the beginning.",
                    isCorrect = false,
                    feedback = "Starting over may create duplicate or inconsistent transactions. OWASP A10 recommends safe handling of exceptional states. Stop and report the failed transaction with details.",
                ),
            ),
        ),
    )

    val totalModules: Int = modules.size

    fun findModule(id: String): OwaspTrainingModule? =
        modules.firstOrNull { it.id == id }
}
