"""
SENTRY — Middleware Server Entry Point
=======================================
FastAPI application that serves as the bridge between
Timothy's Pepper/NAOqi layer and Derick's RAG AI engine.

The middleware:
    - Exposes REST endpoints that Pepper calls over the local network
    - Validates all incoming requests before they reach the AI engine
    - Initialises the RAGPipeline once at startup (expensive operation)
      and reuses it across all requests
    - Returns structured JSON responses that Pepper can parse

Start the server:
    uvicorn middleware.main:app --reload --host 0.0.0.0 --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from middleware.routes.query_routes import router as query_router
from config.settings import settings


# ------------------------------------------------------------------
# Pipeline — initialised once at startup, shared across all requests
# ------------------------------------------------------------------

# We store the pipeline on app.state so routes can access it
# without importing a global — cleaner and testable.
pipeline_instance = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan handler.
    Runs startup logic before the server begins accepting requests,
    and cleanup logic when the server shuts down.
    """
    # Startup
    print("[SENTRY Middleware] Starting up...")
    settings.validate()

    from ai_engine.rag.pipeline import RAGPipeline
    app.state.pipeline = RAGPipeline()
    print(
        f"[SENTRY Middleware] Server ready on "
        f"{settings.MIDDLEWARE_HOST}:{settings.MIDDLEWARE_PORT}"
    )

    yield  # Server is running — handle requests

    # Shutdown
    print("[SENTRY Middleware] Shutting down.")


# ------------------------------------------------------------------
# FastAPI app
# ------------------------------------------------------------------

app = FastAPI(
    title="SENTRY Middleware API",
    description=(
        "REST API bridge between the Pepper robot (Timothy's HRI layer) "
        "and the RAG AI engine (Derick's grounding layer). "
        "Provides grounded and baseline cybersecurity query endpoints."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Allow requests from Pepper's local IP and any dev tools
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Tighten to Pepper's IP in production
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# Register route modules
app.include_router(query_router, prefix="/api/v1")


# ------------------------------------------------------------------
# Root health check — Timothy can ping this to confirm server is up
# ------------------------------------------------------------------

@app.get("/", tags=["Health"])
async def root():
    return {
        "service": "SENTRY Middleware",
        "status": "running",
        "version": "1.0.0",
    }


@app.get("/health", tags=["Health"])
async def health():
    """
    Health check endpoint.
    Pepper calls this on startup to confirm the AI backend is reachable.
    """
    pipeline = getattr(app.state, "pipeline", None)
    stats = {}

    if pipeline:
        stats = pipeline._retriever.get_collection_stats()

    return {
        "status": "healthy",
        "pipeline_ready": pipeline is not None,
        "knowledge_base": stats,
    }